# OneHotEncoder() 

`OneHotEncoder()`를 활용하여 범주형 자료를 더미화하는 방법 중 하나입니다. 서로 다른 데이터셋에서 적용할 때의 모습을 살펴보겠습니다.

> 1. handle_unknown : 'ignore'
> 2. handle_unknown : 'error'

***

#### 데이터 만들기 

In [3]:
import pandas as pd

In [4]:
data = {'Wealth':[27, 32],
        'bld':['A',  'O']}

train = pd.DataFrame(data, index = ['Salah', 'Anuj'])

In [5]:
data = {'Wealth':[51,  22],
        'bld':['A', 'B']}

test = pd.DataFrame(data, index = ['Hwan', 'Jason'])

In [6]:
train

Wealth bld
Salah      27   A
Anuj       32   O

In [7]:
test

Wealth bld
Hwan       51   A
Jason      22   B

***

###  OneHotEncoder(handle_unknown="ignore")

In [9]:
from sklearn.preprocessing import OneHotEncoder

In [24]:
encoder = OneHotEncoder(handle_unknown="ignore", sparse = False)
encoder.fit(train[['bld']])

OneHotEncoder(categorical_features=None, categories=None, drop=None,
              dtype=<class 'numpy.float64'>, handle_unknown='ignore',
              n_values=None, sparse=False)

In [27]:
encoder.transform(train[['bld']])

array([[1., 0.],
       [0., 1.]])

In [28]:
encoder.transform(test[['bld']])

array([[1., 0.],
       [0., 0.]])

새로운 값 B를 마주하자, 모든 벡터를 0으로 표기하였다.

***

###  OneHotEncoder(handle_unknown="error")

> 원래 error가 default 값이기도 하다.

In [29]:
from sklearn.preprocessing import OneHotEncoder

In [30]:
encoder = OneHotEncoder( sparse = False)
encoder.fit(train[['bld']])

OneHotEncoder(categorical_features=None, categories=None, drop=None,
              dtype=<class 'numpy.float64'>, handle_unknown='error',
              n_values=None, sparse=False)

In [31]:
encoder.transform(train[['bld']])

array([[1., 0.],
       [0., 1.]])

In [32]:
encoder.transform(test[['bld']])

ValueError: Found unknown categories ['B'] in column 0 during transform

> error가 반환됨을 확인할 수 있다.